/system/fonts/custom/
/system/fonts/AndroidClock.ttf
/system/fonts/CarroisGothicSC-Regular.ttf
/system/fonts/CNZ_ExtraLight.ttf
/system/fonts/CNZ_SemiBold.ttf
/system/fonts/CNZH_Light.ttf
/system/fonts/CNZI_ExtraLight.ttf
/system/fonts/ComingSoon.ttf
/system/fonts/CutiveMono.ttf
/system/fonts/DancingScript-Bold.ttf
/system/fonts/DancingScript-Regular.ttf
/system/fonts/DroidSans.ttf
/system/fonts/DroidSans-Bold.ttf
/system/fonts/DroidSansMono.ttf
/system/fonts/HYZhengYuan-Bold.ttf
/system/fonts/HYZhengYuan-Light.ttf
/system/fonts/HYZhengYuan-Medium.ttf
/system/fonts/HYZhengYuan-Regular.ttf
/system/fonts/NotoColorEmoji.ttf
/system/fonts/NotoColorEmojiFlags.ttf
/system/fonts/NotoColorEmojiLegacy.ttf
/system/fonts/NotoNaskhArabic-Bold.ttf
/system/fonts/NotoNaskhArabic-Regular.ttf
/system/fonts/NotoNaskhArabicUI-Bold.ttf
/system/fonts/NotoNaskhArabicUI-Regular.ttf
/system/fonts/NotoSansAdlam-VF.ttf
/system/fonts/NotoSansAhom-Regular.otf
/system/fonts/NotoSansAnatolianHieroglyphs-Regular.otf
/system/fonts/NotoSansArmenian-VF.ttf
/system/fonts/NotoSansAvestan-Regular.ttf
/system/fonts/NotoSansBalinese-Regular.ttf
/system/fonts/NotoSansBamum-Regular.ttf
/system/fonts/NotoSansBassaVah-Regular.otf
/system/fonts/NotoSansBatak-Regular.ttf
/system/fonts/NotoSansBengali-VF.ttf
/system/fonts/NotoSansBengaliUI-VF.ttf
/system/fonts/NotoSansBhaiksuki-Regular.otf
/system/fonts/NotoSansBrahmi-Regular.ttf
/system/fonts/NotoSansBuginese-Regular.ttf
/system/fonts/NotoSansBuhid-Regular.ttf
/system/fonts/NotoSansCanadianAboriginal-Regular.ttf
/system/fonts/NotoSansCarian-Regular.ttf
/system/fonts/NotoSansChakma-Regular.otf
/system/fonts/NotoSansCham-Bold.ttf
/system/fonts/NotoSansCham-Regular.ttf
/system/fonts/NotoSansCherokee-Regular.ttf
/system/fonts/NotoSansCJK-Black.ttc
/system/fonts/NotoSansCJK-Bold.ttc
/system/fonts/NotoSansCJK-DemiLight.ttc
/system/fonts/NotoSansCJK-Light.ttc
/system/fonts/NotoSansCJK-Medium.ttc
/system/fonts/NotoSansCJK-Regular.ttc
/system/fonts/NotoSansCJK-Thin.ttc
/system/fonts/NotoSansCoptic-Regular.ttf
/system/fonts/NotoSansCuneiform-Regular.ttf
/system/fonts/NotoSansCypriot-Regular.ttf
/system/fonts/NotoSansDeseret-Regular.ttf
/system/fonts/NotoSansDevanagari-VF.ttf
/system/fonts/NotoSansDevanagariUI-VF.ttf
/system/fonts/NotoSansEgyptianHieroglyphs-Regular.ttf
/system/fonts/NotoSansElbasan-Regular.otf
/system/fonts/NotoSansEthiopic-VF.ttf
/system/fonts/NotoSansGeorgian-VF.ttf
/system/fonts/NotoSansGlagolitic-Regular.ttf
/system/fonts/NotoSansGothic-Regular.ttf
/system/fonts/NotoSansGrantha-Regular.ttf
/system/fonts/NotoSansGujarati-Bold.ttf
/system/fonts/NotoSansGujarati-Regular.ttf
/system/fonts/NotoSansGujaratiUI-Bold.ttf
/system/fonts/NotoSansGujaratiUI-Regular.ttf
/system/fonts/NotoSansGunjalaGondi-Regular.otf
/system/fonts/NotoSansGurmukhi-VF.ttf
/system/fonts/NotoSansGurmukhiUI-VF.ttf
/system/fonts/NotoSansHanifiRohingya-Regular.otf
/system/fonts/NotoSansHanunoo-Regular.ttf
/system/fonts/NotoSansHatran-Regular.otf
/system/fonts/NotoSansHebrew-Bold.ttf
/system/fonts/NotoSansHebrew-Regular.ttf
/system/fonts/NotoSansImperialAramaic-Regular.ttf
/system/fonts/NotoSansInscriptionalPahlavi-Regular.ttf
/system/fonts/NotoSansInscriptionalParthian-Regular.ttf
/system/fonts/NotoSansJavanese-Regular.otf
/system/fonts/NotoSansKaithi-Regular.ttf
/system/fonts/NotoSansKannada-VF.ttf
/system/fonts/NotoSansKannadaUI-VF.ttf
/system/fonts/NotoSansKayahLi-Regular.ttf
/system/fonts/NotoSansKharoshthi-Regular.ttf
/system/fonts/NotoSansKhmer-VF.ttf
/system/fonts/NotoSansKhmerUI-Bold.ttf
/system/fonts/NotoSansKhmerUI-Regular.ttf
/system/fonts/NotoSansKhojki-Regular.otf
/system/fonts/NotoSansLao-Bold.ttf
/system/fonts/NotoSansLao-Regular.ttf
/system/fonts/NotoSansLaoUI-Bold.ttf
/system/fonts/NotoSansLaoUI-Regular.ttf
/system/fonts/NotoSansLepcha-Regular.ttf
/system/fonts/NotoSansLimbu-Regular.ttf
/system/fonts/NotoSansLinearA-Regular.otf
/system/fonts/NotoSansLinearB-Regular.ttf
/system/fonts/NotoSansLisu-Regular.ttf
/system/fonts/NotoSansLycian-Regular.ttf
/system/fonts/NotoSansLydian-Regular.ttf
/system/fonts/NotoSansMalayalam-VF.ttf
/system/fonts/NotoSansMalayalamUI-VF.ttf
/system/fonts/NotoSansMandaic-Regular.ttf
/system/fonts/NotoSansManichaean-Regular.otf
/system/fonts/NotoSansMarchen-Regular.otf
/system/fonts/NotoSansMasaramGondi-Regular.otf
/system/fonts/NotoSansMedefaidrin-VF.ttf
/system/fonts/NotoSansMeeteiMayek-Regular.ttf
/system/fonts/NotoSansMeroitic-Regular.otf
/system/fonts/NotoSansMiao-Regular.otf
/system/fonts/NotoSansModi-Regular.ttf
/system/fonts/NotoSansMongolian-Regular.ttf
/system/fonts/NotoSansMro-Regular.otf
/system/fonts/NotoSansMultani-Regular.otf
/system/fonts/NotoSansMyanmar-Bold.otf
/system/fonts/NotoSansMyanmar-Medium.otf
/system/fonts/NotoSansMyanmar-Regular.otf
/system/fonts/NotoSansMyanmarUI-Bold.otf
/system/fonts/NotoSansMyanmarUI-Medium.otf
/system/fonts/NotoSansMyanmarUI-Regular.otf
/system/fonts/NotoSansNabataean-Regular.otf
/system/fonts/NotoSansNewa-Regular.otf
/system/fonts/NotoSansNewTaiLue-Regular.ttf
/system/fonts/NotoSansNKo-Regular.ttf
/system/fonts/NotoSansOgham-Regular.ttf
/system/fonts/NotoSansOlChiki-Regular.ttf
/system/fonts/NotoSansOldItalic-Regular.ttf
/system/fonts/NotoSansOldNorthArabian-Regular.otf
/system/fonts/NotoSansOldPermic-Regular.otf
/system/fonts/NotoSansOldPersian-Regular.ttf
/system/fonts/NotoSansOldSouthArabian-Regular.ttf
/system/fonts/NotoSansOldTurkic-Regular.ttf
/system/fonts/NotoSansOriya-Bold.ttf
/system/fonts/NotoSansOriya-Regular.ttf
/system/fonts/NotoSansOriyaUI-Bold.ttf
/system/fonts/NotoSansOriyaUI-Regular.ttf
/system/fonts/NotoSansOsage-Regular.ttf
/system/fonts/NotoSansOsmanya-Regular.ttf
/system/fonts/NotoSansPahawhHmong-Regular.otf
/system/fonts/NotoSansPalmyrene-Regular.otf
/system/fonts/NotoSansPauCinHau-Regular.otf
/system/fonts/NotoSansPhagsPa-Regular.ttf
/system/fonts/NotoSansPhoenician-Regular.ttf
/system/fonts/NotoSansRejang-Regular.ttf
/system/fonts/NotoSansRunic-Regular.ttf
/system/fonts/NotoSansSamaritan-Regular.ttf
/system/fonts/NotoSansSaurashtra-Regular.ttf
/system/fonts/NotoSansSharada-Regular.otf
/system/fonts/NotoSansShavian-Regular.ttf
/system/fonts/NotoSansSinhala-VF.ttf
/system/fonts/NotoSansSinhalaUI-VF.ttf
/system/fonts/NotoSansSoraSompeng-Regular.otf
/system/fonts/NotoSansSoyombo-VF.ttf
/system/fonts/NotoSansSundanese-Regular.ttf
/system/fonts/NotoSansSylotiNagri-Regular.ttf
/system/fonts/NotoSansSymbols-Regular-Subsetted.ttf
/system/fonts/NotoSansSymbols-Regular-Subsetted2.ttf
/system/fonts/NotoSansSyriacEastern-Regular.ttf
/system/fonts/NotoSansSyriacEstrangela-Regular.ttf
/system/fonts/NotoSansSyriacWestern-Regular.ttf
/system/fonts/NotoSansTagalog-Regular.ttf
/system/fonts/NotoSansTagbanwa-Regular.ttf
/system/fonts/NotoSansTaiLe-Regular.ttf
/system/fonts/NotoSansTaiTham-Regular.ttf
/system/fonts/NotoSansTaiViet-Regular.ttf
/system/fonts/NotoSansTakri-VF.ttf
/system/fonts/NotoSansTamil-VF.ttf
/system/fonts/NotoSansTamilUI-VF.ttf
/system/fonts/NotoSansTelugu-VF.ttf
/system/fonts/NotoSansTeluguUI-VF.ttf
/system/fonts/NotoSansThaana-Bold.ttf
/system/fonts/NotoSansThaana-Regular.ttf
/system/fonts/NotoSansThai-Bold.ttf
/system/fonts/NotoSansThai-Regular.ttf
/system/fonts/NotoSansThaiUI-Bold.ttf
/system/fonts/NotoSansThaiUI-Regular.ttf
/system/fonts/NotoSansTifinagh-Regular.otf
/system/fonts/NotoSansUgaritic-Regular.ttf
/system/fonts/NotoSansVai-Regular.ttf
/system/fonts/NotoSansWancho-Regular.otf
/system/fonts/NotoSansWarangCiti-Regular.otf
/system/fonts/NotoSansYi-Regular.ttf
/system/fonts/NotoSerif-Bold.ttf
/system/fonts/NotoSerif-BoldItalic.ttf
/system/fonts/NotoSerif-Italic.ttf
/system/fonts/NotoSerif-Regular.ttf
/system/fonts/NotoSerifArmenian-VF.ttf
/system/fonts/NotoSerifBengali-VF.ttf
/system/fonts/NotoSerifCJK-Regular.ttc
/system/fonts/NotoSerifDevanagari-VF.ttf
/system/fonts/NotoSerifDogra-Regular.ttf
/system/fonts/NotoSerifEthiopic-VF.ttf
/system/fonts/NotoSerifGeorgian-VF.ttf
/system/fonts/NotoSerifGujarati-VF.ttf
/system/fonts/NotoSerifGurmukhi-VF.ttf
/system/fonts/NotoSerifHebrew-Bold.ttf
/system/fonts/NotoSerifHebrew-Regular.ttf
/system/fonts/NotoSerifKannada-VF.ttf
/system/fonts/NotoSerifKhmer-Bold.otf
/system/fonts/NotoSerifKhmer-Regular.otf
/system/fonts/NotoSerifLao-Bold.ttf
/system/fonts/NotoSerifLao-Regular.ttf
/system/fonts/NotoSerifMalayalam-VF.ttf
/system/fonts/NotoSerifMyanmar-Bold.otf
/system/fonts/NotoSerifMyanmar-Regular.otf
/system/fonts/NotoSerifNyiakengPuachueHmong-VF.ttf
/system/fonts/NotoSerifSinhala-VF.ttf
/system/fonts/NotoSerifTamil-VF.ttf
/system/fonts/NotoSerifTelugu-VF.ttf
/system/fonts/NotoSerifThai-Bold.ttf
/system/fonts/NotoSerifThai-Regular.ttf
/system/fonts/NotoSerifTibetan-VF.ttf
/system/fonts/NotoSerifYezidi-VF.ttf
/system/fonts/Roboto-Regular.ttf
/system/fonts/RobotoStatic-Regular.ttf
/system/fonts/SourceSansPro-Bold.ttf
/system/fonts/SourceSansPro-BoldItalic.ttf
/system/fonts/SourceSansPro-Italic.ttf
/system/fonts/SourceSansPro-Regular.ttf
/system/fonts/SourceSansPro-SemiBold.ttf
/system/fonts/SourceSansPro-SemiBoldItalic.ttf
/system/fonts/ZDigit-Bold.ttf
/system/fonts/ZDigit-Light.ttf
/system/fonts/ZDigit-Medium.ttf
/system/fonts/ZDigit-Regular.ttf
/system/fonts/ZDigit-Thin.ttf
