package terminal.emulator

import android.content.Context
import android.content.pm.PackageManager
import android.util.Log
import rikka.shizuku.Shizuku
import java.io.File
import java.io.RandomAccessFile

/**
 * DESIGN Shizuku switch: privileged prefix shells (nix proot cannot exec in the app domain —
 * untrusted_app W^X denies it with EACCES/126, device verified). The Shizuku server runs the prefix
 * login with the PTY as its stdio via the official rish loader (app_process + rish_shizuku.dex).
 */
object ShizukuGate {
    private const val TAG = "ShizukuGate"
    const val WRAPPER_NAME = "shizuku-login.sh"
    private const val RISH_ASSET = "rish_shizuku.dex"

    // Binder failures surface as RemoteException/SecurityException/IllegalStateException depending on
    // manager state; a failed check must read as unauthorized, never crash startup.
    @Suppress("TooGenericExceptionCaught")
    fun isAuthorized(): Boolean = try {
        Shizuku.pingBinder() && Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED
    } catch (exception: Exception) {
        Log.w(TAG, "Shizuku check failed", exception)
        false
    }

    @Suppress("TooGenericExceptionCaught")
    fun requestPermission() {
        try {
            Shizuku.requestPermission(0)
        } catch (exception: Exception) {
            Log.w(TAG, "Shizuku request failed", exception)
        }
    }

    /**
     * Ensure the rish dex + login wrapper exist. The wrapper runs under /system/bin/sh (allowed) and
     * execs the system app_process (allowed); the dex talks to the Shizuku server as this package
     * (granted via the manager) and runs the prefix login with this PTY as stdio.
     *
     * A nix-built login entry may be a dynamically linked ELF whose INTERP points into /nix/store
     * (absent on Android — exec then dies with ENOENT "No such file"). In that case the wrapper
     * chain-loads it through the prefix's own glibc loader with the closure lib dirs on the search
     * path; scripts and static binaries exec directly.
     */
    fun ensureWrapper(context: Context, prefixDir: String): File {
        val rishDir = File(context.filesDir, "rish")
        rishDir.mkdirs()
        val dex = File(rishDir, "rish_shizuku.dex")
        context.assets.open(RISH_ASSET).use { input ->
            val bytes = input.readBytes()
            if (!dex.isFile || !dex.readBytes().contentEquals(bytes)) {
                dex.writeBytes(bytes)
            }
        }
        // Android 14+: app_process refuses to load a writable dex.
        dex.setWritable(false, false)
        dex.setWritable(false, true)
        val wrapper = File(context.filesDir, WRAPPER_NAME)
        val login = File(prefixDir, "bin/login").absolutePath
        val launch = chainLoadPrefix(login, prefixDir) ?: "exec $login"
        // NOTE: $launch must never contain quotes: it is embedded in a single-quoted
        // rish -c argument, and any inner quote breaks the server-side parse.
        val content =
            "#!/system/bin/sh\n" +
                "# Generated by torvox, do not edit: Shizuku login wrapper.\n" +
                "export RISH_APPLICATION_ID=\"com.termux\"\n" +
                "exec /system/bin/app_process" +
                " -Djava.class.path=\"${dex.absolutePath}\"" +
                " /system/bin --nice-name=rish" +
                " rikka.shizuku.shell.ShizukuShellLoader -c '$launch'\n"
        if (!wrapper.isFile || wrapper.readText() != content) {
            wrapper.writeText(content)
            wrapper.setExecutable(true)
        }
        return wrapper
    }

    /**
     * When [loginPath] is a dynamically linked ELF with a /nix/store INTERP, return a shell command
     * that chain-loads it through the prefix glibc loader; null means exec directly. Pure Kotlin ELF
     * sniffing (64-bit program headers) — no native code, no new dependencies.
     */
    internal fun chainLoadPrefix(loginPath: String, prefixDir: String): String? {
        if (!readInterp(loginPath).startsWith("/nix/store/")) return null
        // Store paths never contain spaces or quotes; refuse rather than misquote.
        if (loginPath.any { it == ' ' || it == '\'' || it == '"' }) return null
        val storeDir = File(prefixDir, "nix/store")
        val libDirs =
            storeDir
                .listFiles()
                ?.mapNotNull { entry ->
                    val lib = File(entry, "lib")
                    if (lib.isDirectory) lib.absolutePath else null
                }
                ?.sorted() ?: return null
        val loader =
            libDirs
                .asSequence()
                .map { File(it) }
                .flatMap { (it.listFiles() ?: emptyArray()).toList() }
                .firstOrNull {
                    it.name.startsWith("ld-linux-") &&
                        (it.name.endsWith(".so.1") || it.name.endsWith(".so.2"))
                } ?: return null
        // Lib dirs are enumerated here (not globbed at runtime) so the -c payload
        // stays quote-free and survives every shell layer verbatim.
        return "exec ${loader.absolutePath} --library-path ${libDirs.joinToString(":")} $loginPath"
    }

    /** 64-bit ELF program-header table location. */
    private data class ElfProgramHeaders(val offset: Long, val entrySize: Int, val count: Int)

    private fun readU16(data: ByteArray, at: Int): Int = (data[at].toInt() and 0xff) or ((data[at + 1].toInt() and 0xff) shl 8)

    internal fun readU32(data: ByteArray, at: Int): Long {
        var value = 0L
        for (shift in 0 until 4) value = value or ((data[at + shift].toLong() and 0xff) shl (8 * shift))
        return value
    }

    internal fun readU64(data: ByteArray, at: Int): Long {
        var value = 0L
        for (shift in 0 until 8) value = value or ((data[at + shift].toLong() and 0xff) shl (8 * shift))
        return value
    }

    /** Validate 64-bit ELF magic; return the program-header table location. */
    private fun elfProgramHeaders(header: ByteArray): ElfProgramHeaders? {
        if (header.size < 64) return null
        val magic =
            header[0] == 0x7f.toByte() &&
                header[1] == 'E'.code.toByte() &&
                header[2] == 'L'.code.toByte() &&
                header[3] == 'F'.code.toByte() &&
                header[4] == 2.toByte()
        if (!magic) return null
        // e_phoff(0x20 u64) e_phentsize(0x36 u16) e_phnum(0x38 u16).
        val table =
            ElfProgramHeaders(readU64(header, 0x20), readU16(header, 0x36), readU16(header, 0x38))
        if (table.entrySize < 56 || table.count <= 0 || table.count > 32) return null
        return table
    }

    /** File offset of the PT_INTERP string, or -1 when the table has none. */
    internal fun findInterpOffset(entries: ByteArray, entrySize: Int, count: Int): Long {
        // 64-bit Phdr: p_type(4) p_flags(4) p_offset(8) ...
        for (index in 0 until count) {
            val base = index * entrySize
            if (readU32(entries, base) != 3L) continue // PT_INTERP
            return readU64(entries, base + 8)
        }
        return -1
    }

    /** Read a NUL-terminated string at a file offset. */
    internal fun readCString(file: RandomAccessFile, offset: Long): String {
        file.seek(offset)
        val name = ByteArray(512)
        val length = file.read(name)
        if (length <= 0) return ""
        return name.decodeToString(0, length).trimEnd('\u0000').lineSequence().first()
    }

    /** Read the PT_INTERP string of a 64-bit ELF, or "" when absent/unreadable. */
    internal fun readInterp(path: String): String = try {
        RandomAccessFile(path, "r").use { file ->
            val header = ByteArray(64)
            if (file.read(header) < 64) return ""
            val table = elfProgramHeaders(header) ?: return ""
            val entries = ByteArray(table.entrySize * table.count)
            file.seek(table.offset)
            var got = 0
            while (got < entries.size) {
                val read = file.read(entries, got, entries.size - got)
                if (read < 0) return ""
                got += read
            }
            val offset = findInterpOffset(entries, table.entrySize, table.count)
            if (offset < 0) "" else readCString(file, offset)
        }
    } catch (exception: java.io.IOException) {
        Log.w(TAG, "readInterp failed", exception)
        ""
    }
}
