package terminal.emulator

import android.content.Context
import android.content.pm.PackageManager
import android.util.Log
import java.io.File
import rikka.shizuku.Shizuku

/**
 * DESIGN Shizuku switch: privileged prefix shells (nix proot cannot exec in the app domain —
 * untrusted_app W^X denies it with EACCES/126, device verified). The Shizuku server runs the prefix
 * login with the PTY as its stdio via the official rish loader (app_process + rish_shizuku.dex).
 */
object ShizukuGate {
  private const val TAG = "ShizukuGate"
  const val WRAPPER_NAME = "shizuku-login.sh"
  private const val RISH_ASSET = "rish_shizuku.dex"

  fun isAuthorized(): Boolean =
      try {
        Shizuku.pingBinder() && Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED
      } catch (exception: Exception) {
        Log.w(TAG, "Shizuku check failed", exception)
        false
      }

  fun requestPermission() {
    try {
      Shizuku.requestPermission(0)
    } catch (exception: Exception) {
      Log.w(TAG, "Shizuku request failed", exception)
    }
  }

  /**
   * Ensure the rish dex + login wrapper exist. The wrapper runs under /system/bin/sh (allowed) and
   * execs the system app_process (allowed); the dex talks to the Shizuku server as this package
   * (granted via the manager) and runs the prefix login with this PTY as stdio.
   */
  fun ensureWrapper(context: Context, prefixDir: String): File {
    val rishDir = File(context.filesDir, "rish")
    rishDir.mkdirs()
    val dex = File(rishDir, "rish_shizuku.dex")
    context.assets.open(RISH_ASSET).use { input ->
      val bytes = input.readBytes()
      if (!dex.isFile || !dex.readBytes().contentEquals(bytes)) {
        dex.writeBytes(bytes)
      }
    }
    // Android 14+: app_process refuses to load a writable dex.
    dex.setWritable(false, false)
    dex.setWritable(false, true)
    val wrapper = File(context.filesDir, WRAPPER_NAME)
    val login = File(prefixDir, "bin/login").absolutePath
    val content =
        "#!/system/bin/sh\n" +
            "# Generated by torvox, do not edit: Shizuku login wrapper.\n" +
            "export RISH_APPLICATION_ID=\"com.termux\"\n" +
            "exec /system/bin/app_process" +
            " -Djava.class.path=\"${dex.absolutePath}\"" +
            " /system/bin --nice-name=rish" +
            " rikka.shizuku.shell.ShizukuShellLoader -c \"exec '$login'\"\n"
    if (!wrapper.isFile || wrapper.readText() != content) {
      wrapper.writeText(content)
      wrapper.setExecutable(true)
    }
    return wrapper
  }
}
