package terminal.emulator

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** ShizukuGate wrapper renderer: exact script shape, parameters embedded verbatim. */
class ShizukuGateTest {

    @Test
    fun wrapperContent_exactShape() {
        assertEquals(
            """
            #!/system/bin/sh
            # Generated by terminal, do not edit: Shizuku login wrapper.
            export RISH_APPLICATION_ID="terminal.emulator"
            exec /system/bin/app_process -Djava.class.path="/dex/rish_shizuku.dex" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader -c 'exec /prefix/bin/login'
            """.trimIndent() + "\n",
            ShizukuGate.wrapperContent("terminal.emulator", "/dex/rish_shizuku.dex", "exec /prefix/bin/login"),
        )
    }

    @Test
    fun wrapperContent_embedsParametersVerbatim() {
        val content = ShizukuGate.wrapperContent("com.example", "/d/dex", "exec /p/bin/bash")
        assertTrue(content.startsWith("#!/system/bin/sh\n"))
        assertTrue(content.contains("export RISH_APPLICATION_ID=\"com.example\""))
        assertTrue(content.contains("-c 'exec /p/bin/bash'"))
        assertTrue(content.endsWith("\n") && !content.endsWith("\n\n"))
    }
}
