[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
description = "Integration tests terminal emulator"

[dependencies]
native = { workspace = true, features = ["test-util"] }

[dev-dependencies]
toml = { workspace = true }
wgpu = { workspace = true }
futures = { workspace = true }
regex-lite = "0.1"

[lints]
workspace = true
