name: check
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/kudzu
          path: result-kudzu
      - uses: ./result-kudzu/.github/actions/install-nix
      - run: rm -rf result-kudzu
      - uses: cachix/cachix-action@master
        continue-on-error: true
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/cache/restore@main
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/wrapper/dists
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            ~/.cargo/git
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-
      - env:
          CARGO_INCREMENTAL: "0"
        run: |
          scripts/check-rust.nu
          scripts/build-android-libs.nu x86_64
          scripts/check-gradle.nu
      - uses: actions/cache/save@main
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/wrapper/dists
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            ~/.cargo/git
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
