name: check
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/kudzu
          path: result-kudzu
      - uses: ./result-kudzu/.github/actions/install-nix
      - uses: cachix/cachix-action@master
        continue-on-error: true
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/cache/restore@main
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-
      - env:
          CARGO_INCREMENTAL: "0"
        run: |
          scripts/check-rust.nu
          nix develop --command cargo build --package native
          scripts/build-android-libs.nu --profile dev x86_64
          scripts/check-gradle.nu
      - uses: actions/cache/save@main
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
