name: fmt
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  fmt:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/kudzu
          path: result-kudzu
      - uses: ./result-kudzu/.github/actions/install-nix
      - uses: cachix/cachix-action@master
        continue-on-error: true
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/cache/restore@main
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-
      - run: |
          set -e
          rm -f ~/.config/nix/nix.conf
          nix flake update
          nix develop --command markdownlint-cli2 --fix "**/*.md"
          nix develop --command cargo fmt --all -v
          nix develop --command cargo clippy --workspace --all-targets --fix --allow-dirty
          nix develop --command bash -c "pushd android && ./gradlew spotlessApply && ./gradlew detekt --auto-correct && popd"
          nix fmt
          git add .
          git commit --amend --no-edit
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
      - uses: actions/cache/save@main
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
